# Generated by Django 4.1.3 on 2022-11-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consertmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('SingerName', models.CharField(max_length=100)),
                ('Length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='locationmodel',
            fields=[
                ('IdNumbers', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(default='تهران برج میلاد', max_length=500)),
                ('Phone', models.CharField(max_length=11, null=True)),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatetime', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('concertmodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.consertmodel')),
                ('locationmodel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.locationmodel')),
            ],
        ),
    ]
