# Generated by Django 4.1.3 on 2022-11-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0002_concertmodel_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=100)),
                ('ProfiletImage', models.ImageField(upload_to='profileimages/')),
                ('Gender', models.IntegerField(verbose_name=(('Man', 'مرد'), ('Woman', 'زن')))),
            ],
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='ConcertImage',
            field=models.ImageField(null=True, upload_to='concertimages/'),
        ),
        migrations.CreateModel(
            name='ticketmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('TicketImage', models.ImageField(upload_to='ticketimages/')),
                ('ProfileModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.profilemodel')),
                ('TimeModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.timemodel')),
            ],
        ),
    ]
