# Generated by Django 4.1.3 on 2022-11-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0003_profilemodel_concertmodel_concertimage_ticketmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'مکان', 'verbose_name_plural': 'مکان'},
        ),
        migrations.RemoveField(
            model_name='consertmodel',
            name='ConcertImage',
        ),
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
        migrations.AddField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='concertimages/', verbose_name='\u200d\u200d\u200d\u200d\u200d\u200d\u200d\u200d\u200dپوستر'),
        ),
        migrations.AlterField(
            model_name='consertmodel',
            name='Length',
            field=models.IntegerField(verbose_name=' مدت زمان'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='خواننده'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='تهران برج میلاد', max_length=500, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='IdNumbers',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد محل'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Family',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[('Man', 'مرد'), ('Woman', 'زن')], verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='ProfiletImage',
            field=models.ImageField(upload_to='profileimages/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ProfileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.profilemodel', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TicketImage',
            field=models.ImageField(upload_to='ticketimages/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TimeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.timemodel', verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='ConcertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='LocationModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.locationmodel', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seats',
            field=models.IntegerField(verbose_name='صندلی'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='تایم شروع'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='status',
            field=models.IntegerField(choices=[('Start', 'فروش بلیط شروع شده است'), ('End', 'فروش بلیط تمام شده است'), ('Cancle', 'این سانس کنسل شده است'), ('Sales', 'در حال فروش بلیط')], verbose_name='وضعیت'),
        ),
    ]
