# Generated by Django 4.1.3 on 2022-12-01 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0004_alter_consertmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='concertmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام کنسرت')),
                ('SingerName', models.CharField(max_length=100, verbose_name='خواننده')),
                ('Length', models.IntegerField(verbose_name=' مدت زمان')),
                ('Poster', models.ImageField(null=True, upload_to='concertimages/', verbose_name='\u200d\u200d\u200d\u200d\u200d\u200d\u200d\u200d\u200dپوستر')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'زمان', 'verbose_name_plural': 'زمان'},
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='ConcertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.concertmodel', verbose_name='کنسرت'),
        ),
        migrations.DeleteModel(
            name='consertmodel',
        ),
    ]
